import os; os.makedirs('src/uiao_core/freshness', exist_ok=True)
lines = []
lines.append("from __future__ import annotations")
lines.append("")
lines.append("from dataclasses import dataclass")
lines.append("from datetime import datetime, timezone")
lines.append("from typing import Dict, List, Optional")
lines.append("")
lines.append("from uiao_core.governance.actions import GovernanceAction")
lines.append("from uiao_core.ir.models.core import Evidence")
lines.append("")
lines.append("DEFAULT_THRESHOLDS: Dict[str, int] = {")
lines.append("    \"AC\": 30, \"AU\": 7, \"CA\": 90, \"CM\": 14,")
lines.append("    \"IA\": 30, \"IR\": 1, \"RA\": 90, \"SC\": 30,")
lines.append("    \"SI\": 7, \"default\": 30,")
lines.append("}")
lines.append("")
lines.append("")
lines.append("@dataclass(frozen=True)")
lines.append("class FreshnessRecord:")
lines.append("    evidence_id: str")
lines.append("    control_id: str")
lines.append("    age_days: float")
lines.append("    threshold_days: int")
lines.append("    status: str")
lines.append("    generated_at: str")
lines.append("")
lines.append("")
lines.append("def parseiso(ts: str) -> datetime:")
lines.append("    try:")
lines.append("        dt = datetime.fromisoformat(ts)")
lines.append("    except Exception:")
lines.append("        dt = datetime.strptime(ts, \"%Y-%m-%dT%H:%M:%SZ\").replace(tzinfo=timezone.utc)")
lines.append("    if dt.tzinfo is None:")
lines.append("        dt = dt.replace(tzinfo=timezone.utc)")
lines.append("    return dt")
lines.append("")
lines.append("")
lines.append("def classify_age(age_days: float, threshold: int) -> str:")
lines.append("    if age_days <= threshold:")
lines.append("        return \"fresh\"")
lines.append("    if age_days <= threshold * 1.5:")
lines.append("        return \"stale-soon\"")
lines.append("    return \"stale\"")
lines.append("")
lines.append("")
lines.append("def build_freshness_records(")
lines.append("    evidence_list: List[Evidence],")
lines.append("    thresholds: Optional[Dict[str, int]] = None,")
lines.append("    now: Optional[datetime] = None,")
lines.append(") -> List[FreshnessRecord]:")
lines.append("    thr = thresholds or DEFAULT_THRESHOLDS")
lines.append("    now = now or datetime.now(timezone.utc)")
lines.append("    records: List[FreshnessRecord] = []")
lines.append("    for e in evidence_list:")
lines.append("        ts = e.timestamp or (e.data.get(\"timestamp\") if e.data else None)")
lines.append("        if not ts:")
lines.append("            age_days: float = float(\"inf\")")
lines.append("        else:")
lines.append("            age_days = (now - parseiso(ts)).total_seconds() / 86400.0")
lines.append("        control_id = e.control_id or (e.data.get(\"ksi_id\", \"UNKNOWN\") if e.data else \"UNKNOWN\")")
lines.append("        family = control_id.split(\"-\")[0] if \"-\" in control_id else control_id[:2]")
lines.append("        threshold = thr.get(control_id) or thr.get(family) or thr.get(\"default\", 30)")
lines.append("        records.append(FreshnessRecord(")
lines.append("            evidence_id=e.id,")
lines.append("            control_id=control_id,")
lines.append("            age_days=age_days,")
lines.append("            threshold_days=threshold,")
lines.append("            status=classify_age(age_days, threshold),")
lines.append("            generated_at=now.isoformat(),")
lines.append("        ))")
lines.append("    return records")
lines.append("")
lines.append("")
lines.append("def generate_refresh_actions(")
lines.append("    freshness_records: List[FreshnessRecord],")
lines.append("    existing_actions: List[GovernanceAction],")
lines.append("    default_owner: str = \"security-ops@org.gov\",")
lines.append("    sla_days_for_stale: int = 7,")
lines.append(") -> List[GovernanceAction]:")
lines.append("    existing_keys = {(a.evidence_id, a.action_type) for a in existing_actions}")
lines.append("    actions: List[GovernanceAction] = []")
lines.append("    for r in freshness_records:")
lines.append("        if r.status != \"stale\":")
lines.append("            continue")
lines.append("        if (r.evidence_id, \"refresh\") in existing_keys:")
lines.append("            continue")
lines.append("        age_str = \"{:.1f}\".format(r.age_days)")
lines.append("        desc = \"Refresh evidence \" + r.evidence_id + \" for control \" + r.control_id + \", age \" + age_str + \" days\"")
lines.append("        actions.append(GovernanceAction(")
lines.append("            ksi_id=r.control_id,")
lines.append("            control_id=r.control_id,")
lines.append("            policy_id=\"policy:freshness:auto\",")
lines.append("            severity=\"Medium\",")
lines.append("            drift_classification=\"stale_evidence\",")
lines.append("            owner=default_owner,")
lines.append("            sla_days=sla_days_for_stale,")
lines.append("            action_type=\"refresh\",")
lines.append("            description=desc,")
lines.append("            evidence_id=r.evidence_id,")
lines.append("        ))")
lines.append("    return actions")
open("src/uiao_core/freshness/engine.py", "w", encoding="utf-8").write("\n".join(lines) + "\n")
print("engine.py written")
