#!/usr/bin/env python3
"""spec_test_coverage_check.py — UIAO_103 CI gate.

Re-runs ``spec_test_audit.py`` and compares the result against the
committed coverage table at ``docs/docs/governance/spec-test-coverage.md``.

Two modes:

    --check   (default) — fail with diff if any spec's invariant count
                          dropped vs the committed baseline. New invariants
                          are allowed (they raise the bar; future PRs add
                          tests + update the table).

    --update             — rewrite the auto-generated section of the
                           coverage table from the live audit. Used by
                           authors after they add new normative statements
                           or wire new tests to existing ones.

The coverage table has two sections:

  1. ``## Invariant inventory (auto-generated)`` — table managed by this
     script. Anything between the ``<!-- BEGIN AUTO -->`` and
     ``<!-- END AUTO -->`` markers is overwritten on ``--update``.

  2. ``## Coverage map (manual)`` — a YAML block in a fenced section
     mapping ``document_id`` → list of test files / pytest nodeids that
     target the spec's invariants. Maintained by humans; never touched
     by this script.

Pipeline:

    src/uiao/canon/specs/*.md
            │
            ▼
    spec_test_audit.py rollup
            │
            ▼
    spec_test_coverage_check.py --check
            │  diff vs docs/docs/governance/spec-test-coverage.md
            ▼
    PR pass / fail

Exit codes:
    0 — coverage baseline preserved (or --update succeeded)
    1 — coverage shrunk; PR should be blocked
    2 — bad input / table malformed
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# Re-use the audit tool by import. The tool is also fully usable as a
# stand-alone CLI; this gate just calls audit() + rollup() in-process.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from spec_test_audit import (  # noqa: E402
    REPO_ROOT,
    SpecRollup,
    audit,
    rollup,
)

DEFAULT_COVERAGE_PATH = REPO_ROOT / "docs" / "docs" / "governance" / "spec-test-coverage.md"

_AUTO_BEGIN = "<!-- BEGIN AUTO -->"
_AUTO_END = "<!-- END AUTO -->"

_TABLE_HEADER = "| document_id | file | total | by_kind |"
_TABLE_DIVIDER = "|---|---|---:|---|"
_TABLE_ROW_RE = re.compile(
    r"^\|\s*(?P<doc>[\w_-]+)\s*\|\s*(?P<file>[^|]+?)\s*\|\s*"
    r"(?P<total>\d+)\s*\|\s*(?P<by_kind>[^|]*?)\s*\|\s*$"
)


def _format_by_kind(by_kind: dict[str, int]) -> str:
    if not by_kind:
        return "—"
    return ", ".join(f"{k}={v}" for k, v in sorted(by_kind.items()))


def _parse_by_kind(text: str) -> dict[str, int]:
    if not text or text.strip() == "—":
        return {}
    out: dict[str, int] = {}
    for token in text.split(","):
        token = token.strip()
        if not token or "=" not in token:
            continue
        k, v = token.split("=", 1)
        try:
            out[k.strip()] = int(v.strip())
        except ValueError:
            continue
    return out


def render_auto_block(rollups: list[SpecRollup]) -> str:
    """Produce the auto-generated table content (no markers)."""
    lines = [
        "_This table is auto-generated by `scripts/tools/spec_test_audit.py`._",
        "",
        _TABLE_HEADER,
        _TABLE_DIVIDER,
    ]
    for r in rollups:
        lines.append(f"| {r.document_id} | `{r.file}` | {r.total} | {_format_by_kind(r.by_kind)} |")
    if not rollups:
        lines.append("| _(no canon specs with normative statements yet)_ | | 0 | — |")
    lines.append("")
    lines.append(f"**Total invariants tracked:** {sum(r.total for r in rollups)}")
    lines.append(f"**Specs with at least one invariant:** {len(rollups)}")
    return "\n".join(lines)


def parse_committed_table(path: Path) -> dict[str, dict[str, int]]:
    """Parse the committed AUTO block. Returns ``{document_id: {kind: count}}``.

    Missing or malformed table → empty dict (treat as baseline zero).
    """
    if not path.is_file():
        return {}
    text = path.read_text(encoding="utf-8")
    if _AUTO_BEGIN not in text or _AUTO_END not in text:
        return {}
    block = text.split(_AUTO_BEGIN, 1)[1].split(_AUTO_END, 1)[0]

    out: dict[str, dict[str, int]] = {}
    for line in block.splitlines():
        m = _TABLE_ROW_RE.match(line)
        if not m:
            continue
        doc = m.group("doc")
        out[doc] = _parse_by_kind(m.group("by_kind"))
    return out


def diff_baselines(
    committed: dict[str, dict[str, int]],
    live: list[SpecRollup],
) -> list[str]:
    """Return human-readable failure reasons. Empty list = baseline preserved."""
    failures: list[str] = []
    live_by_doc = {r.document_id: r for r in live}

    # 1. Specs that lost invariants.
    for doc, committed_kinds in committed.items():
        committed_total = sum(committed_kinds.values())
        live_rollup = live_by_doc.get(doc)
        live_total = live_rollup.total if live_rollup else 0
        if live_total < committed_total:
            failures.append(f"{doc}: invariant count shrank from {committed_total} to {live_total}")

    # 2. Specs newly missing entirely.
    for doc in committed:
        if doc not in live_by_doc and sum(committed[doc].values()) > 0:
            failures.append(f"{doc}: was tracked with invariants but no longer present in audit")

    return failures


def write_updated_table(path: Path, rollups: list[SpecRollup]) -> None:
    """Rewrite the AUTO block in-place. Manual sections are preserved."""
    if not path.is_file():
        # Bootstrap a minimal scaffold so first-run --update produces a
        # valid table. Author refines the manual section after.
        path.parent.mkdir(parents=True, exist_ok=True)
        scaffold = _scaffold(rollups)
        path.write_text(scaffold, encoding="utf-8")
        return

    text = path.read_text(encoding="utf-8")
    if _AUTO_BEGIN not in text or _AUTO_END not in text:
        # Markers missing — bootstrap into a fresh scaffold while
        # preserving any pre-existing prose by appending it after.
        path.write_text(_scaffold(rollups) + "\n\n---\n\n" + text, encoding="utf-8")
        return

    head, _, rest = text.partition(_AUTO_BEGIN)
    _, _, tail = rest.partition(_AUTO_END)
    new_text = head + _AUTO_BEGIN + "\n" + render_auto_block(rollups) + "\n" + _AUTO_END + tail
    path.write_text(new_text, encoding="utf-8")


def _scaffold(rollups: list[SpecRollup]) -> str:
    """First-run scaffold for the coverage table."""
    return f"""---
title: "UIAO_103 Spec-Test Coverage"
description: "Auto-generated invariant inventory + manual test-coverage map."
uiao.id: governance-spec-test-coverage
uiao.status: Current
provenance:
  derived_from:
    - src/uiao/canon/specs/*.md
    - src/uiao/canon/UIAO_*.md
  derived_by: scripts/tools/spec_test_audit.py
---

# UIAO_103 Spec-Test Coverage

This page tracks two artifacts:

1. **Invariant inventory** — every RFC 2119 normative keyword (MUST,
   SHALL, REQUIRED, MUST NOT, SHALL NOT, RECOMMENDED, SHOULD) found in
   canonical spec markdown. Auto-generated by
   `scripts/tools/spec_test_audit.py`. Re-run on every PR; the
   coverage gate enforces that **per-spec invariant counts never
   shrink**.

2. **Coverage map** — manually maintained mapping from spec
   `document_id` to the test files (or pytest nodeids) that exercise
   its invariants. Authors update this when wiring new tests.

## Invariant inventory (auto-generated)

{_AUTO_BEGIN}
{render_auto_block(rollups)}
{_AUTO_END}

## Coverage map (manual)

```yaml
# document_id → tests that exercise its invariants. Pytest nodeids
# accepted: tests/test_foo.py or tests/test_foo.py::test_specific_invariant.
# The CI gate does not validate these paths — author discipline is the
# enforcement mechanism. Keep entries sorted by document_id.

UIAO_100:
  - tests/test_orchestrator_scheduler.py
  - tests/test_e2e.py::TestOrchestratorSchedulerE2E
  - tests/test_terraform_scheduler_integration.py

UIAO_113:
  - tests/test_evidence_graph.py
  - tests/test_evidence_graph_scheduler.py
  - tests/test_evidence_graph_drift_semantic.py

UIAO_016:
  # DRIFT-SEMANTIC freshness evaluator
  - tests/test_drift_semantic_freshness.py
```

## Maintenance

- **Add a normative invariant to a spec.** No action required. The audit
  picks it up on the next PR. The coverage gate accepts the count
  growing.
- **Lose a normative invariant.** Either the gate fires (count shrinks
  → PR fails) or the loss is intentional (spec retired); update the
  committed table with `python scripts/tools/spec_test_coverage_check.py
  --update` and explain in the PR description.
- **Wire a test that exercises a spec.** Add the test path under the
  appropriate `document_id` in the coverage map. The map is
  documentation; no automation reads it.

## CI

The `spec-test-coverage.yml` workflow runs on every PR touching canon
specs or this file. Failure modes:

- Spec's invariant count dropped → block.
- Spec previously tracked is missing entirely → block.
- New invariant added → pass (with a notice listing the new lines).
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--coverage-file",
        type=Path,
        default=DEFAULT_COVERAGE_PATH,
        help=f"Path to the coverage table (default: {DEFAULT_COVERAGE_PATH.relative_to(REPO_ROOT)})",
    )
    parser.add_argument(
        "--update",
        action="store_true",
        help="Rewrite the AUTO block from the live audit. Author tool, not CI gate.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Emit diff result as JSON instead of human text.",
    )
    args = parser.parse_args(argv)

    invariants = audit()
    rollups = rollup(invariants)

    if args.update:
        write_updated_table(args.coverage_file, rollups)
        rel = args.coverage_file.relative_to(REPO_ROOT) if args.coverage_file.is_absolute() else args.coverage_file
        print(f"updated {rel}: {len(rollups)} specs, {sum(r.total for r in rollups)} invariants")
        return 0

    committed = parse_committed_table(args.coverage_file)
    failures = diff_baselines(committed, rollups)

    if args.json:
        json.dump(
            {
                "passed": not failures,
                "committed_specs": len(committed),
                "live_specs": len(rollups),
                "live_total": sum(r.total for r in rollups),
                "failures": failures,
            },
            sys.stdout,
            indent=2,
        )
        sys.stdout.write("\n")
        return 0 if not failures else 1

    if failures:
        print("UIAO_103 spec-test coverage gate FAILED:")
        for f in failures:
            print(f"  ✗ {f}")
        print()
        print("To accept the change (e.g., spec retired or merged), run:")
        print("    python scripts/tools/spec_test_coverage_check.py --update")
        print("and explain in the PR description.")
        return 1

    print(
        f"UIAO_103 spec-test coverage gate OK — {len(rollups)} specs / "
        f"{sum(r.total for r in rollups)} invariants tracked, baseline preserved."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
