#!/usr/bin/env python3
"""Render Vol VII Book 06's catalog tables from the Lane F control map.

The map (`servicenow-day2/saas-control-map.json`) is the SSOT for what each
catalog item is, who approves it, how it actuates, and which control it closes.
The book's phase tables are a *projection* of that — so they must be generated,
not typed.

They were typed once, on 2026-07-14, and that is the reason this exists: a
hand-written projection of an SSOT is the same defect as the Vol 0 Book 02
master table and the stale prose counts. It reads correctly on the day it is
written and silently lies the first time the map changes.

Each item carries `phase` (which table it belongs to) and `summary` (the table
cell). `summary` is authored for the table rather than truncated out of `note`
— an earlier version of this generator took `note.split(".")[0]` and produced
cells reading "THE GATE." and "SCIM path only.", which is what made hand-writing
look like the better option. It was not; the field was.

Usage:
    python render_book_catalog.py            # inject into the book
    python render_book_catalog.py --check    # drift gate (exit 1 if stale)
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
MAP = HERE / "servicenow-day2" / "saas-control-map.json"
BOOK = HERE / "Vol_VII_Book_06_FedAAN_SaaS_Integration_Governance.qmd"

BEGIN = "<!-- catalog:begin — generated by render_book_catalog.py from servicenow-day2/saas-control-map.json; do not hand-edit -->"
END = "<!-- catalog:end -->"

# Per-phase framing. Keyed by the `phase` value in the map; the generator fails
# loudly on an unknown phase rather than silently dropping the items.
PHASE_BLURB = {
    "1 — Intake and authorization": "Nothing is configured here. This phase answers *may this integration happen at all*, and records the answer before anyone can act on the opposite.",
    "2 — Register and configure": "The integration becomes a governed object — a reconciled CI and an approved change — before it becomes a federation trust.",
    "3 — Credentials": "The SAML signing certificate and the SCIM bearer token are authenticators with lifecycles, not setup steps. This is Lane E's rule applied to the federation trust.",
    "4 — Provision and authorize": "Only now does directory data move, and only under an approved scoping filter and attribute mapping.",
    "5 — Lifecycle (joiner/mover/leaver)": "The HR system owns the fact (Book 04); this lane is where the fact reaches the SaaS.",
    "6 — Evidence": "Collection is not review. Both are catalog items, because only an owned task proves somebody looked.",
    "7 — Attest and exit": "Authorization is not a one-time fact, and the step most often skipped is the last one.",
}

# Callouts that belong with a phase but are argument, not data — so they stay
# authored here rather than in the map.
PHASE_CALLOUT = {
    "5 — Lifecycle (joiner/mover/leaver)": (
        "callout-important",
        "**This phase is why the others matter.** Without it the directory is clean and the vendor "
        "still holds a live account — the precise failure an assessor probes, and the one an "
        "ungoverned portal-click integration guarantees. Separation is not network-observable: "
        "absence of logins is indistinguishable from leave. Only an event-driven feed from the "
        "owner of the fact starts the revocation on time.",
    ),
    "6 — Evidence": (
        "callout-warning",
        "**Boundary caveat on `saas.logs`.** This collects what the tenant can see; it does not "
        "conjure what the boundary withholds. GCC-Moderate telemetry limits bound what reaches the "
        "SIEM in the first place — see the SCuBA boundary-limitations analysis. A ConMon claim built "
        "on this must state that limit rather than imply completeness.",
    ),
    "7 — Attest and exit": (
        "callout-note",
        "**Authorization is not a one-time fact.** A CSO can lose its authorization; an integration "
        "can outlive its business need. `saas.offboard` is the step most often skipped — an "
        "integration nobody uses still holds a live directory replica and a valid signing certificate.",
    ),
}

_NECESSITY = {"SA-9"}  # marked † in the tables; the anchor is argued in the book's prose


def load() -> dict:
    return json.loads(MAP.read_text(encoding="utf-8"))["catalog"]


def render() -> str:
    cat = load()
    missing = [k for k, v in cat.items() if not v.get("phase") or not v.get("summary")]
    if missing:
        raise SystemExit(f"control map items missing phase/summary: {missing}")
    unknown = {v["phase"] for v in cat.values()} - set(PHASE_BLURB)
    if unknown:
        raise SystemExit(f"control map uses unknown phase(s): {sorted(unknown)}")

    L: list[str] = [BEGIN, ""]
    n_items = len(cat)
    n_ctrl = len({v["control"] for v in cat.values()})
    L.append(f"# The Catalog — {n_items} Governed Items, {n_ctrl} Controls")
    L.append("")
    L.append(
        "The ordering is the control. **The authorization verdict is recorded before anything is "
        "configured**, because a verdict collected afterward is a rationalization, not a gate."
    )
    L.append("")
    L.append(
        "Every row below is generated from `servicenow-day2/saas-control-map.json`, which the CI "
        "check validates against the spine — the book cannot drift from the map it describes."
    )
    L.append("")

    for phase in PHASE_BLURB:  # dict order == phase order
        items = [(k, v) for k, v in cat.items() if v["phase"] == phase]
        if not items:
            continue
        L.append(f"## Phase {phase}")
        L.append("")
        L.append(PHASE_BLURB[phase])
        L.append("")
        L.append("| Catalog item | What happens | Approval | Control |")
        L.append("|---|---|---|---|")
        for k, v in items:
            ctrl = v["control"] + (" †" if v["control"] in _NECESSITY else "")
            approval = v["approval"].replace("_", " ").replace("+", " + ")
            L.append(f"| `{k}` | {v['summary']} | {approval} | **{ctrl}** |")
        # Per the Vol 0 Book 02 convention, Vol VII/IX rows record where a control is
        # coordinated, evidenced and operated — not a second independent closure. SA-9
        # is the sole primary closure ("closed here first"); the rest are operationalized.
        necessity = [v["control"] for _, v in items if v["control"] in _NECESSITY]
        others = [v["control"] for _, v in items if v["control"] not in _NECESSITY]
        segs: list[str] = []
        if necessity:
            segs.append("closes " + ", ".join(f"**{c}** †" for c in necessity))
        if others:
            segs.append("operationalizes " + ", ".join(f"**{c}**" for c in others))
        L.append("")
        L.append(f": Phase {phase.split(' — ')[0]} — {'; '.join(segs)} {{.striped .hover}}")
        L.append("")
        if phase in PHASE_CALLOUT:
            cls, body = PHASE_CALLOUT[phase]
            L.append(f"::: {{.{cls}}}")
            L.append(body)
            L.append(":::")
            L.append("")
    L.append(END)
    return "\n".join(L)


def book_with_block(block: str) -> str:
    t = BOOK.read_text(encoding="utf-8")
    if BEGIN in t and END in t:
        return t[: t.index(BEGIN)] + block + t[t.index(END) + len(END) :]
    # first run: replace the hand-written catalog section wholesale
    m = re.search(r"^# The Catalog — .*?(?=^# The Control Map)", t, re.M | re.S)
    if not m:
        raise SystemExit("cannot locate the catalog section to replace; add the markers by hand")
    return t[: m.start()] + block + "\n\n" + t[m.end() :]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    ap.add_argument("--check", action="store_true", help="drift gate (exit 1 if stale)")
    args = ap.parse_args()
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    block = render()
    new = book_with_block(block)
    if args.check:
        if BOOK.read_text(encoding="utf-8") != new:
            print(f"DRIFT — regenerate: python {Path(__file__).name}")
            return 1
        print(f"OK — {BOOK.name} catalog tables match the Lane F control map.")
        return 0
    BOOK.write_text(new, encoding="utf-8")
    cat = load()
    print(
        f"Wrote the catalog block into {BOOK.name} ({len(cat)} items, {len({v['control'] for v in cat.values()})} controls)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
