<#
.SYNOPSIS
    Convert [IMAGE-NN: ...] placeholders to Quarto figure blocks after PNGs
    have been generated by scripts/generate_images.py.

.DESCRIPTION
    For every .qmd under docs/customer-documents/, scans for [IMAGE-NN: <prompt>]
    placeholders that have a matching generated PNG. Match is via the sibling
    images/<name>.png.json sidecar's `placeholder_id` field (the generator
    writes one sidecar per PNG with a stable placeholder_id like "IMAGE-03").

    Each matched placeholder is replaced in place with a Quarto figure block:

        ![<short caption>](images/<png>){#fig-<docslug>-image-NN
            fig-alt="<full prompt body>" width="85%"}

    The short caption is the first sentence of the prompt (everything up to
    the first '.'), truncated to 80 chars. The fig-alt preserves the FULL
    prompt body so the generator cache key (hash of placeholder body) keeps
    matching if you ever re-run generation.

    Idempotent. Safe to re-run:
      - Placeholders without a matching sidecar are left in place (reported).
      - Already-converted figures (![](...) blocks) are not re-processed.
      - Re-running on a doc that's already been converted is a no-op.

.PARAMETER Root
    Override the customer-documents root.

.PARAMETER Section
    Limit to one section under customer-documents/.

.PARAMETER DryRun
    Print planned edits without writing any files.

.PARAMETER VerifyOnly
    Don't modify any files; only report which placeholders WOULD convert
    (sidecar present) vs. which would NOT (no sidecar yet).

.EXAMPLE
    pwsh scripts/Convert-ImagePlaceholdersToFigures.ps1 -VerifyOnly
    Show per-doc match counts without modifying anything.

.EXAMPLE
    pwsh scripts/Convert-ImagePlaceholdersToFigures.ps1 -DryRun
    Show what would change, file-by-file.

.EXAMPLE
    pwsh scripts/Convert-ImagePlaceholdersToFigures.ps1 -Section whitepapers

.NOTES
    Exit codes:
      0   all placeholders converted (or no placeholders found)
      1   at least one placeholder lacked a matching sidecar — re-run the
          generator to fill the gap, then re-run this script
      2   precondition failure (root path missing)
#>
[CmdletBinding()]
param(
    [string]$Root,
    [string]$Section,
    [switch]$DryRun,
    [switch]$VerifyOnly
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 3.0

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
if (-not $Root) {
    $Root = Join-Path $repoRoot 'docs\customer-documents'
}
if ($Section) {
    $Root = Join-Path $Root $Section
}
if (-not (Test-Path $Root)) {
    Write-Error "Root not found: $Root"
    exit 2
}

$excludeDirs   = @('_freeze', '_site', '.quarto', 'node_modules', '__pycache__')
# Greedy-but-bounded match: from `[IMAGE-NN: ` to the first `]` on the same
# block. Placeholder bodies span multiple lines, so we use a single-line
# (DOTALL-equivalent) construct that stops at the matching close-bracket.
$placeholderRx = [regex]::new(
    '\[IMAGE-(?<num>\d+):\s+(?<body>(?:[^\[\]]|\[(?!IMAGE-\d+:))+?)\]',
    [System.Text.RegularExpressions.RegexOptions]::Singleline
)

function Pad2 { param([int]$n) ([string]$n).PadLeft(2, '0') }
function PadL { param($v, [int]$w) ([string]$v).PadLeft($w, ' ') }

function Test-PathInExcludedDir {
    param([string]$AbsPath, [string]$Base, [string[]]$Excluded)
    $rel = $AbsPath.Substring($Base.Length).TrimStart('\','/')
    $sep = @([IO.Path]::DirectorySeparatorChar, [IO.Path]::AltDirectorySeparatorChar)
    foreach ($seg in $rel.Split($sep)) {
        if ($Excluded -contains $seg) { return $true }
    }
    return $false
}

function Get-DocSlug {
    param([string]$QmdFileName)
    return [IO.Path]::GetFileNameWithoutExtension($QmdFileName)
}

function Get-ShortCaption {
    param([string]$PromptBody)
    $firstSentence = ($PromptBody -split '\.', 2)[0]
    $firstSentence = ($firstSentence -replace '\s+', ' ').Trim()
    if ($firstSentence.Length -gt 80) {
        $firstSentence = $firstSentence.Substring(0, 80).TrimEnd() + '...'
    }
    return $firstSentence
}

$qmds = @(Get-ChildItem -Path $Root -Filter '*.qmd' -Recurse -File -ErrorAction SilentlyContinue |
    Where-Object { -not (Test-PathInExcludedDir -AbsPath $_.FullName -Base $Root -Excluded $excludeDirs) })

$totalConverted = 0
$totalUnmatched = 0
$docsTouched    = 0

foreach ($q in $qmds) {
  try {
    $text = Get-Content -Path $q.FullName -Raw -Encoding UTF8
    if (-not $text) { continue }
    $phMatches = $placeholderRx.Matches($text)
    if ($phMatches.Count -eq 0) { continue }

    # Build sidecar map for this doc's sibling images/ dir.
    $imagesDir  = Join-Path $q.DirectoryName 'images'
    $sidecarMap = @{}
    if (Test-Path $imagesDir) {
        $sidecars = @(Get-ChildItem -Path $imagesDir -Filter '*.png.json' -File -ErrorAction SilentlyContinue)
        foreach ($sc in $sidecars) {
            try {
                $meta = Get-Content -Path $sc.FullName -Raw -Encoding UTF8 | ConvertFrom-Json
            } catch { continue }
            if ($meta.PSObject.Properties.Name -contains 'placeholder_id') {
                $key = $meta.placeholder_id.ToUpper()
                $sidecarMap[$key] = @{
                    Sidecar = $sc
                    Png     = $sc.FullName.Substring(0, $sc.FullName.Length - 5)  # strip ".json"
                    Meta    = $meta
                }
            }
        }
    }

    $docSlug   = Get-DocSlug -QmdFileName $q.Name
    $changes   = New-Object System.Collections.Generic.List[hashtable]
    $unmatched = 0

    foreach ($m in $phMatches) {
        $num  = [int]$m.Groups['num'].Value
        $body = $m.Groups['body'].Value.Trim()
        $phId = ("IMAGE-{0:D2}" -f $num)

        if (-not $sidecarMap.ContainsKey($phId)) {
            $unmatched++
            continue
        }

        $entry   = $sidecarMap[$phId]
        $pngFile = [IO.Path]::GetFileName($entry.Png)
        $relPng  = "images/$pngFile"
        $caption = Get-ShortCaption -PromptBody $body
        $padded  = Pad2 $num
        $figId   = "fig-$docSlug-image-$padded"

        # Escape double quotes inside fig-alt by backslash.
        $altEscaped = $body -replace '"', '\"'

        $figureBlock = "![$caption]($relPng){#$figId fig-alt=`"$altEscaped`" width=`"85%`"}"

        $changes.Add(@{
            Index  = $m.Index
            Length = $m.Length
            Block  = $figureBlock
            Num    = $num
            Png    = $pngFile
        }) | Out-Null
    }

    if ($changes.Count -eq 0 -and $unmatched -eq 0) { continue }

    $rel = $q.FullName.Substring($repoRoot.Path.Length).TrimStart('\','/').Replace('\','/')

    if ($VerifyOnly) {
        $color = if ($unmatched -gt 0) { 'Yellow' } else { 'Green' }
        Write-Host "  $rel : $($changes.Count) ready, $unmatched unmatched" -ForegroundColor $color
        $totalConverted += $changes.Count
        $totalUnmatched += $unmatched
        continue
    }

    if ($changes.Count -eq 0) {
        Write-Host "  $rel : 0 ready, $unmatched unmatched (skipping write)" -ForegroundColor Yellow
        $totalUnmatched += $unmatched
        continue
    }

    # Apply replacements end-to-start so each match's Index stays valid.
    $sorted  = $changes | Sort-Object { $_.Index } -Descending
    $newText = $text
    foreach ($c in $sorted) {
        $newText = $newText.Substring(0, $c.Index) + $c.Block + $newText.Substring($c.Index + $c.Length)
    }

    $cnt = PadL $changes.Count 2
    if ($DryRun) {
        Write-Host "  WOULD convert $cnt placeholder(s) in $rel  (unmatched: $unmatched)" -ForegroundColor Yellow
    } else {
        Set-Content -Path $q.FullName -Value $newText -Encoding UTF8 -NoNewline
        Write-Host "  Converted    $cnt placeholder(s) in $rel  (unmatched: $unmatched)" -ForegroundColor Green
    }

    $totalConverted += $changes.Count
    $totalUnmatched += $unmatched
    $docsTouched++
  }
  catch {
    $relPath = $q.FullName.Substring($repoRoot.Path.Length).TrimStart('\','/').Replace('\','/')
    Write-Warning "Error processing $relPath : $($_.Exception.Message)"
    continue
  }
}

Write-Host ""
$verb = if ($DryRun -or $VerifyOnly) { 'Would convert' } else { 'Converted' }
$summaryColor = if ($totalUnmatched -gt 0) { 'Yellow' } else { 'Green' }
Write-Host "$verb $totalConverted placeholder(s) across $docsTouched doc(s)    Unmatched: $totalUnmatched" -ForegroundColor $summaryColor

if ($totalUnmatched -gt 0) { exit 1 } else { exit 0 }
