#!/usr/bin/env python3
"""Generate the spine-derived control crosswalk from the compliance spine.

The hand-maintained master crosswalk in
`Vol_0_Book_02_OrgComp_Control_Crosswalk.qmd` indexes the full series control
set — but most of those rows are hand-authored, because the spine only
carries closure rows for the books that have been back-filled. This renders
the slice the spine *can* prove: for every control that appears in a spine
closure, the volume/book(s) where it is closed, its family, whether it is a
Closure-Necessity anchor, and the FedRAMP 20x KSI theme(s) it maps to.

It is the machine-derived companion to the hand-maintained master table, and
it is CI-gated the same way the per-book authorities tables are — so as the
spine is back-filled book by book, this crosswalk grows toward the full master
automatically and can never silently drift from the spine.

Coverage is stated honestly up top: this is NOT series-wide control coverage,
it is the coverage the spine can currently prove.

Usage:
    python render_crosswalk.py            # write OrgComp_Spine_Crosswalk.md
    python render_crosswalk.py --check     # drift gate (exit 1 if stale)
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML required: pip install pyyaml")

HERE = Path(__file__).resolve().parent
SPINE = HERE / "orgcomp-compliance-spine.yml"
OUT = HERE / "OrgComp_Spine_Crosswalk.md"

# The master crosswalk book. Its hand-maintained table is the superset of
# controls the series addresses; the "not yet closed" appendix below is rendered
# into it as the set difference (master − spine closures), between these markers.
BOOK02 = HERE / "Vol_0_Book_02_OrgComp_Control_Crosswalk.qmd"


def master_control_count() -> int:
    """Count the control rows in the hand-maintained master crosswalk table, so
    prose that cites the master's size tracks it automatically instead of drifting."""
    text = BOOK02.read_text(encoding="utf-8")
    return len(set(re.findall(r"^\|\s*\*\*([A-Z]{2}-[0-9][0-9A-Za-z()\-]*)\*\*", text, re.M)))


NC_BEGIN = "<!-- not-closed:begin — generated by render_crosswalk.py; do not hand-edit -->"
NC_END = "<!-- not-closed:end -->"

# A master-table control row: | **AC-2(1)** | Title | AC | Vol I Bk 01 | KSI-IAM |
_MASTER_ROW = re.compile(
    r"^\|\s*\*\*([A-Z]{2}-\d+(?:\(\d+\))?)\*\*\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|",
    re.M,
)

# Volume id -> roman label used in the "Where addressed" cells. The series
# numbers Volume 0 as the Executive Summary & Program volume.
ROMAN = {
    "vol-0": "0",
    "vol-1": "I",
    "vol-2": "II",
    "vol-3": "III",
    "vol-4": "IV",
    "vol-5": "V",
    "vol-6": "VI",
    "vol-7": "VII",
    "vol-8": "VIII",
    "vol-9": "IX",
    "vol-10": "X",
}
# Roman -> sort rank so "Where addressed" and the coverage table order by volume.
ROMAN_RANK = {r: i for i, r in enumerate(ROMAN.values())}


def load_spine(path: Path = SPINE) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def _book_volume(spine: dict) -> dict[str, str]:
    """Map each book id to its owning volume id (authoritative membership)."""
    out: dict[str, str] = {}
    for vol in spine["volumes"]:
        for book_id in vol["books"]:
            out[book_id] = vol["id"]
    return out


def _book_number(book: dict) -> str:
    """Derive a book's within-volume number from its source filename.

    The series' canonical volume/book numbering lives in the source path
    (``Vol_<roman>_Book_<nn>_...`` for in-folder books, ``NN-*.md`` for the
    repo-root DDI chapters), so parse it there and fall back to target_slot.
    """
    base = book.get("source", "").rsplit("/", 1)[-1]
    m = re.match(r"Vol_[IVX0-9]+_Book_([0-9A-Za-z]+)_", base)
    if m:
        return m.group(1)
    m = re.match(r"(\d+)-", base)
    if m:
        return m.group(1)
    if "appendix" in base.lower():
        m = re.search(r"appendix-([A-Za-z0-9]+)", base.lower())
        return m.group(1).upper() if m else "A"
    ts = book.get("target_slot", "")
    return ts.split("-")[-1] if "-" in ts else ts


def book_labels(spine: dict) -> dict[str, tuple[str, str]]:
    """Map book id -> (roman, "Vol <roman> Bk <nn>") for every registered book."""
    vol_of = _book_volume(spine)
    out: dict[str, tuple[str, str]] = {}
    for book in spine["books"]:
        roman = ROMAN.get(vol_of.get(book["id"], ""), "?")
        out[book["id"]] = (roman, f"Vol {roman} Bk {_book_number(book)}")
    return out


def _control_sort_key(control: str) -> tuple[str, int, int]:
    """Natural sort: family, base number, enhancement number."""
    m = re.match(r"([A-Z]+)-(\d+)(?:\((\d+)\))?", control)
    if not m:
        return (control, 0, 0)
    return (m.group(1), int(m.group(2)), int(m.group(3) or 0))


def _family(control: str) -> str:
    m = re.match(r"([A-Z]+)-", control)
    return m.group(1) if m else control


def aggregate(spine: dict) -> list[dict]:
    """Collapse closures into one crosswalk row per control."""
    labels = book_labels(spine)
    by_control: dict[str, dict] = {}
    for c in spine["closures"]:
        ctrl = c["control"]
        row = by_control.setdefault(
            ctrl,
            {
                "control": ctrl,
                "title": c["title"],
                "family": _family(ctrl),
                "books": set(),
                "ksi": set(),
                "necessity": False,
            },
        )
        row["books"].add(labels[c["book"]][1])
        row["ksi"].update(c.get("ksi") or [])
        if c.get("necessity"):
            row["necessity"] = True
    rows = list(by_control.values())
    rows.sort(key=lambda r: _control_sort_key(r["control"]))
    return rows


def _where(books: set[str]) -> str:
    def key(label: str) -> tuple[int, int]:
        m = re.match(r"Vol (\S+) Bk (\w+)", label)
        roman = m.group(1) if m else "?"
        num = m.group(2) if m else "0"
        digits = re.sub(r"\D", "", num) or "0"
        return (ROMAN_RANK.get(roman, 99), int(digits))

    return ", ".join(sorted(books, key=key))


def render() -> str:
    spine = load_spine()
    closures = spine["closures"]
    rows = aggregate(spine)
    total_books = len(spine["books"])
    books_with_closures = sorted({c["book"] for c in closures})
    labels = book_labels(spine)

    L: list[str] = []
    L.append("# AAN Spine-Derived Control Crosswalk")
    L.append("")
    L.append(
        "> **Generated file — do not hand-edit.** Produced by "
        "`render_crosswalk.py` from `orgcomp-compliance-spine.yml`. Regenerate when "
        "closures change; CI-gated by `orgcomp-authorities-drift.yml`."
    )
    L.append("")
    L.append("## Coverage (stated honestly)")
    L.append("")
    L.append(
        f"- This crosswalk is rendered from the **{len(closures)} closure rows** "
        f"the spine carries across **{len(books_with_closures)} of {total_books} "
        "books**. It is the machine-derived slice of the series control "
        "crosswalk — **not** series-wide coverage. The hand-maintained master "
        "table in `Vol_0_Book_02_OrgComp_Control_Crosswalk.qmd` indexes the full "
        f"{master_control_count()} controls across all books; that superset is "
        "author-maintained until the spine back-fill reaches every book."
    )
    L.append(
        f"- It aggregates those closures into **{len(rows)} distinct controls**. "
        "A control closed in several books lists each volume/book. As the spine "
        "is back-filled book by book, this table grows toward the full master "
        "automatically and cannot silently drift from the spine."
    )
    L.append("")
    L.append("## Crosswalk")
    L.append("")
    L.append("| Control | Title | Family | Where addressed (spine) | FedRAMP 20x KSI |")
    L.append("|---|---|---|---|---|")
    for r in rows:
        ctrl = r["control"] + (" †" if r["necessity"] else "")
        ksi = ", ".join(sorted(r["ksi"])) if r["ksi"] else "—"
        L.append(f"| {ctrl} | {r['title']} | {r['family']} | {_where(r['books'])} | {ksi} |")
    L.append("")
    L.append(
        "*† = Closure-Necessity anchor (no alternate closure path; see the "
        "per-book alternate-path rebuttals in the authorities tables).*"
    )
    L.append("")

    # Coverage by volume — distinct controls closed within each volume.
    vol_of = _book_volume(spine)
    by_vol: dict[str, set[str]] = {}
    for c in closures:
        by_vol.setdefault(vol_of.get(c["book"], "?"), set()).add(c["control"])
    L.append("## Control coverage by volume (spine)")
    L.append("")
    L.append(
        "Distinct controls the spine closes within each volume (a control closed "
        "in several volumes is counted in each)."
    )
    L.append("")
    L.append("| Volume | Distinct controls closed |")
    L.append("|---|---|")
    for vol in spine["volumes"]:
        n = len(by_vol.get(vol["id"], set()))
        if n:
            L.append(f"| Vol {ROMAN.get(vol['id'], '?')} | {n} |")
    L.append(f"| **Series total (distinct)** | **{len(rows)}** |")
    L.append("")
    L.append(": Spine control coverage by volume {.striped}")
    L.append("")

    # FedRAMP 20x KSI view — KSI theme -> contributing controls.
    by_ksi: dict[str, set[str]] = {}
    for c in closures:
        for k in c.get("ksi") or []:
            by_ksi.setdefault(k, set()).add(c["control"])
    L.append("## FedRAMP 20x KSI view (spine)")
    L.append("")
    L.append("| FedRAMP 20x KSI | Controls mapped |")
    L.append("|---|---|")
    for ksi in sorted(by_ksi):
        ctrls = ", ".join(sorted(by_ksi[ksi], key=_control_sort_key))
        L.append(f"| **{ksi}** | {ctrls} |")
    L.append("")
    L.append(": FedRAMP 20x Key Security Indicator → contributing controls (spine) {.striped}")
    L.append("")

    # Closure-bearing book roster — makes the 15-of-66 slice explicit.
    L.append("## Closure-bearing books in this slice")
    L.append("")
    title_of = {b["id"]: b["title"] for b in spine["books"]}
    L.append("| Book | Volume/Book | Title |")
    L.append("|---|---|---|")
    for book_id in sorted(books_with_closures, key=lambda b: (ROMAN_RANK.get(labels[b][0], 99), labels[b][1])):
        L.append(f"| {book_id} | {labels[book_id][1]} | {title_of[book_id]} |")
    L.append("")
    return "\n".join(L)


def parse_master(text: str) -> list[tuple[str, str, str, str]]:
    """Parse the hand-maintained master crosswalk rows from Book 02.

    The generated "not yet closed" block is stripped first — it uses the same
    row format, so parsing it back in would count its own output.
    """
    body = text
    if NC_BEGIN in body:
        body = body[: body.index(NC_BEGIN)]
    return [(c, t.strip(), f.strip(), w.strip()) for c, t, f, w in _MASTER_ROW.findall(body)]


def render_not_closed() -> str:
    """Render the master − spine set difference: addressed, not yet closed."""
    spine = load_spine()
    closed = {c["control"] for c in spine["closures"]}
    master = parse_master(BOOK02.read_text(encoding="utf-8"))
    rows = [m for m in master if m[0] not in closed]
    rows.sort(key=lambda r: _control_sort_key(r[0]))

    by_fam: dict[str, int] = {}
    for _c, _t, f, _w in rows:
        by_fam[f] = by_fam.get(f, 0) + 1

    L: list[str] = [NC_BEGIN, ""]
    L.append("# Appendix — Controls Addressed but Not Yet Closed in the Spine")
    L.append("")
    L.append(
        f"Of the **{len(master)} controls** this master table indexes, the compliance "
        f"spine carries a machine-checked closure for **{len(closed)}**. The "
        f"**{len(rows)}** below are addressed somewhere in the series but have **no "
        "spine closure yet** — no generated authorities row, no evidence slot, no "
        "KSI binding, and nothing for the drift gate to check. They are the "
        "back-fill queue."
    )
    L.append("")
    L.append(
        "> **What this table is not.** It is the difference between this book's "
        "hand-maintained index and the spine — **not** a gap analysis against the "
        "FedRAMP Moderate baseline. A control absent from *both* is invisible here: "
        "the series does not carry an authoritative Moderate control list, so "
        '"addressed nowhere" cannot be enumerated from repo data. Read this as '
        '*"claimed in prose, not yet proven by the spine"* — the larger question '
        "of baseline completeness is the SSP's, and is open (see the Vol 0 Book 00 "
        "residual-risk section)."
    )
    L.append("")
    L.append("| Family | Not yet closed |")
    L.append("|---|---|")
    for fam in sorted(by_fam):
        L.append(f"| {fam} | {by_fam[fam]} |")
    L.append(f"| **Total** | **{len(rows)}** |")
    L.append("")
    L.append(": Not-yet-closed controls by family {.striped}")
    L.append("")
    L.append("| Control | Title | Family | Addressed in (this book's index) |")
    L.append("|---|---|---|---|")
    for c, t, f, w in rows:
        L.append(f"| {c} | {t} | {f} | {w} |")
    L.append("")
    L.append(": Controls addressed in the series with no spine closure yet — the back-fill queue {.striped .hover}")
    L.append("")
    L.append(NC_END)
    return "\n".join(L)


def _book02_with_block(block: str) -> str:
    """Return Book 02's text with the not-closed block replaced/appended."""
    text = BOOK02.read_text(encoding="utf-8")
    if NC_BEGIN in text and NC_END in text:
        head = text[: text.index(NC_BEGIN)]
        tail = text[text.index(NC_END) + len(NC_END) :]
        return head + block + tail
    return text.rstrip("\n") + "\n\n" + block + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="drift gate (exit 1 if stale)")
    args = ap.parse_args()
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    content = render()
    block = render_not_closed()
    book02_new = _book02_with_block(block)
    if args.check:
        stale = []
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != content:
            stale.append(OUT.name)
        if BOOK02.read_text(encoding="utf-8") != book02_new:
            stale.append(f"{BOOK02.name} (not-closed appendix)")
        if stale:
            print(f"DRIFT — regenerate: python {Path(__file__).name}  [{', '.join(stale)}]")
            return 1
        print(f"OK — {OUT.name} and the {BOOK02.name} not-closed appendix match the spine.")
        return 0
    OUT.write_text(content, encoding="utf-8")
    BOOK02.write_text(book02_new, encoding="utf-8")
    print(f"Wrote {OUT.name} + the not-closed appendix in {BOOK02.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
