from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Dict, List, Optional

from uiao_core.governance.actions import GovernanceAction
from uiao_core.ir.models.core import Evidence

DEFAULT_THRESHOLDS: Dict[str, int] = {
    "AC": 30, "AU": 7, "CA": 90, "CM": 14,
        "IA": 30, "IR": 1, "RA": 90, "SC": 30,
            "SI": 7, "default": 30,
            }


            @dataclass(frozen=True)
            class FreshnessRecord:
                evidence_id: str
                    control_id: str
                        age_days: float
                            threshold_days: int
                                status: str
                                    generated_at: str


                                    def parseiso(ts: str) -> datetime:
                                        try:
                                                dt = datetime.fromisoformat(ts)
                                                    except Exception:
                                                            dt = datetime.strptime(ts, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
                                                                if dt.tzinfo is None:
                                                                        dt = dt.replace(tzinfo=timezone.utc)
                                                                            return dt


                                                                            def classify_age(age_days: float, threshold: int) -> str:
                                                                                if age_days <= threshold:
                                                                                        return "fresh"
                                                                                            if age_days <= threshold * 1.5:
                                                                                                    return "stale-soon"
                                                                                                        return "stale"
                                                                                                        
                                                                                                        
                                                                                                        def build_freshness_records(
                                                                                                            evidence_list: List[Evidence],
                                                                                                                thresholds: Optional[Dict[str, int]] = None,
                                                                                                                    now: Optional[datetime] = None,
                                                                                                                    ) -> List[FreshnessRecord]:
                                                                                                                        """Compute freshness records for each Evidence item."""
                                                                                                                            thr = thresholds or DEFAULT_THRESHOLDS
                                                                                                                                now = now or datetime.now(timezone.utc)
                                                                                                                                    records: List[FreshnessRecord] = []
                                                                                                                                        for e in evidence_list:
                                                                                                                                                ts = e.timestamp or (e.data.get("timestamp") if e.data else None)
                                                                                                                                                        if not ts:
                                                                                                                                                                    age_days: float = float("inf")
                                                                                                                                                                            else:
                                                                                                                                                                                        age_days = (now - parseiso(ts)).total_seconds() / 86400.0
                                                                                                                                                                                                control_id = e.control_id or (e.data.get("ksi_id", "UNKNOWN") if e.data else "UNKNOWN")
                                                                                                                                                                                                        family = control_id.split("-")[0] if "-" in control_id else control_id[:2]
                                                                                                                                                                                                                threshold = thr.get(control_id) or thr.get(family) or thr.get("default", 30)
                                                                                                                                                                                                                        records.append(FreshnessRecord(
                                                                                                                                                                                                                                    evidence_id=e.id,
                                                                                                                                                                                                                                                control_id=control_id,
                                                                                                                                                                                                                                                            age_days=age_days,
                                                                                                                                                                                                                                                                        threshold_days=threshold,
                                                                                                                                                                                                                                                                                    status=classify_age(age_days, threshold),
                                                                                                                                                                                                                                                                                                generated_at=now.isoformat(),
                                                                                                                                                                                                                                                                                                        ))
                                                                                                                                                                                                                                                                                                            return records
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            def generate_refresh_actions(
                                                                                                                                                                                                                                                                                                                freshness_records: List[FreshnessRecord],
                                                                                                                                                                                                                                                                                                                    existing_actions: List[GovernanceAction],
                                                                                                                                                                                                                                                                                                                        default_owner: str = "security-ops@org.gov",
                                                                                                                                                                                                                                                                                                                            sla_days_for_stale: int = 7,
                                                                                                                                                                                                                                                                                                                            ) -> List[GovernanceAction]:
                                                                                                                                                                                                                                                                                                                                """Produce GovernanceAction with action_type=refresh for stale evidence, deduped against existing."""
                                                                                                                                                                                                                                                                                                                                    existing_keys = {(a.evidence_id, a.action_type) for a in existing_actions}
                                                                                                                                                                                                                                                                                                                                        actions: List[GovernanceAction] = []
                                                                                                                                                                                                                                                                                                                                            for r in freshness_records:
                                                                                                                                                                                                                                                                                                                                                    if r.status != "stale":
                                                                                                                                                                                                                                                                                                                                                                continue
                                                                                                                                                                                                                                                                                                                                                                        if (r.evidence_id, "refresh") in existing_keys:
                                                                                                                                                                                                                                                                                                                                                                                    continue
                                                                                                                                                                                                                                                                                                                                                                                            age_str = "{:.1f}".format(r.age_days)
                                                                                                                                                                                                                                                                                                                                                                                                    desc = "Refresh evidence " + r.evidence_id + " for control " + r.control_id + ", age " + age_str + " days"
                                                                                                                                                                                                                                                                                                                                                                                                            actions.append(GovernanceAction(
                                                                                                                                                                                                                                                                                                                                                                                                                        ksi_id=r.control_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                    control_id=r.control_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                policy_id="policy:freshness:auto",
                                                                                                                                                                                                                                                                                                                                                                                                                                                            severity="Medium",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        drift_classification="stale_evidence",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    owner=default_owner,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sla_days=sla_days_for_stale,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            action_type="refresh",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        description=desc,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    evidence_id=r.evidence_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return actions
