# Write-CanonFiles2.ps1 ? Creates ADR-048, D1.1 discovery scripts, and architecture diagrams
# Run from: C:\Users\whale\git\uiao\tools\
# Usage:    powershell -ExecutionPolicy Bypass -File .\Write-CanonFiles2.ps1

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

param(
    [string]$RepoRoot = "C:\Users\whale\git\uiao"
)

if (-not (Test-Path $RepoRoot)) {
    Write-Error "Repo root not found: $RepoRoot"
    return
}

function Write-B64File {
    param(
        [Parameter(Mandatory)][string]$Base64,
        [Parameter(Mandatory)][string]$TargetPath,
        [string]$Label = $null
    )

    $dir = Split-Path $TargetPath -Parent
    if (-not (Test-Path $dir)) {
        New-Item -Path $dir -ItemType Directory -Force | Out-Null
    }

    if ($Label) {
        Write-Host "Writing $Label..."
    } else {
        Write-Host "Writing $TargetPath..."
    }

    $bytes = [Convert]::FromBase64String($Base64)
    [System.IO.File]::WriteAllBytes($TargetPath, $bytes)

    Write-Host "  OK  $TargetPath" -ForegroundColor Green
}

# --- ADR-048 (OrgPath Attribute Selection) ---
$b64_0 = @"
LS0tCmFkcl9pZDogYWRyLTA0OAp0aXRsZTogIkFEUi0wNDg6IE9yZ1BhdGggQXR0cmlidXRlIFNlbGVjdGlvbiDigJQgZXh0ZW5zaW9uQXR0cmlidXRlcyBvdmVyIEN1c3RvbSBTZWN1cml0eSBBdHRyaWJ1dGVzIgphZHI6ICJBRFItMDQ4IgpzdGF0dXM6IEFjY2VwdGVkCmRhdGU6ICIyMDI2LTA0LTI4IgpkZWNpZGVyczogTWljaGFlbCBTdHJhdHRvbgotLS0KCiMgQURSLTA0ODogT3JnUGF0aCBBdHRyaWJ1dGUgU2VsZWN0aW9uIOKAlCBleHRlbnNpb25BdHRyaWJ1dGVzIG92ZXIgQ3VzdG9tIFNlY3VyaXR5IEF0dHJpYnV0ZXMKCiMjIFN0YXR1cwoKKipBY2NlcHRlZCoqIOKAlCAyMDI2LTA0LTI4CgojIyBDb250ZXh0CgpVSUFPJ3Mgb3JnYW5pemF0aW9uYWwgYWRkcmVzc2luZyBtb2RlbCAoT3JnUGF0aCkgcmVxdWlyZXMgYSBjYW5vbmljYWwgYXR0cmlidXRlIHN0YW1wZWQgb24gZXZlcnkgdXNlciBhbmQgZGV2aWNlIG9iamVjdCBpbiBFbnRyYSBJRC4gVGhpcyBhdHRyaWJ1dGUgZW5jb2RlcyB0aGUgZGV0ZXJtaW5pc3RpYyBvcmdhbml6YXRpb25hbCBwYXRoIChlLmcuLCBgQ09SUC9VUy9FQVNUL0JBTFRJTU9SRS9JVGApIHRoYXQgcmVwbGFjZXMgdGhlIGxlZ2FjeSBBRCBYLjUwMCBPVSB0cmVlLiBPcmdQYXRoIGlzIHRoZSBzaW5nbGUgbW9zdCBjcm9zcy1jdXR0aW5nIGRlY2lzaW9uIGluIHRoZSBpZGVudGl0eSB0cmFuc2Zvcm1hdGlvbiDigJQgaXQgZHJpdmVzIGR5bmFtaWMgZ3JvdXAgbWVtYmVyc2hpcCwgQWRtaW5pc3RyYXRpdmUgVW5pdCBzY29waW5nLCBDb25kaXRpb25hbCBBY2Nlc3MgdGFyZ2V0aW5nLCBJbnR1bmUgU2NvcGUgVGFncywgYW5kIEhSIHByb3Zpc2lvbmluZyBhdHRyaWJ1dGUgbWFwcGluZy4KClRocmVlIGNhbmRpZGF0ZSBhdHRyaWJ1dGUgdHlwZXMgZXhpc3QgaW4gRW50cmEgSUQ6CgoxLiAqKmV4dGVuc2lvbkF0dHJpYnV0ZXMqKiAoZXh0ZW5zaW9uQXR0cmlidXRlMeKAkzE1KSDigJQgRXhjaGFuZ2UgT25saW5lIHNjaGVtYSBhdHRyaWJ1dGVzLCBzeW5jZWQgZnJvbSBBRCB2aWEgRW50cmEgQ29ubmVjdAoyLiAqKkN1c3RvbSBTZWN1cml0eSBBdHRyaWJ1dGVzKiog4oCUIEVudHJhIElEIG5hdGl2ZSwgc3RydWN0dXJlZCBhdHRyaWJ1dGUgc2V0cyB3aXRoIEFCQUMgY2FwYWJpbGl0eQozLiAqKkRpcmVjdG9yeSBFeHRlbnNpb25zKiog4oCUIFJlZ2lzdGVyZWQgdmlhIEdyYXBoIEFQSSBhcHAgcmVnaXN0cmF0aW9uLCB1bmxpbWl0ZWQgY291bnQKClRoZSBkZWNpc2lvbiBtdXN0IHNhdGlzZnkgYWxsIGZpdmUgT3JnUGF0aCBjb25zdW1lcnMgc2ltdWx0YW5lb3VzbHk6Cgp8IENvbnN1bWVyIHwgUmVxdWlyZW1lbnQgfAp8LS0tfC0tLXwKfCBEeW5hbWljIFNlY3VyaXR5IEdyb3VwcyB8IEF0dHJpYnV0ZSBtdXN0IGJlIHVzYWJsZSBpbiBkeW5hbWljIG1lbWJlcnNoaXAgcnVsZXMgZm9yIGJvdGggdXNlcnMgQU5EIGRldmljZXMgfAp8IEFkbWluaXN0cmF0aXZlIFVuaXRzIHwgQXR0cmlidXRlIG11c3QgYmUgdXNhYmxlIGluIGR5bmFtaWMgQVUgbWVtYmVyc2hpcCBydWxlcyB8CnwgQ29uZGl0aW9uYWwgQWNjZXNzIHwgQXR0cmlidXRlIG11c3QgYmUgdXNhYmxlIGluIGRldmljZSBmaWx0ZXIgZXhwcmVzc2lvbnMgfAp8IEludHVuZSBTY29wZSBUYWdzIHwgQXR0cmlidXRlIG11c3QgYmUgcmVhZGFibGUgYnkgSW50dW5lIGZvciBzY29wZSB0YWcgYXNzaWdubWVudCB8CnwgSFIgSW5ib3VuZCBQcm92aXNpb25pbmcgfCBBdHRyaWJ1dGUgbXVzdCBiZSB3cml0YWJsZSBieSBFbnRyYSBJRCBHb3Zlcm5hbmNlIHByb3Zpc2lvbmluZyBmbG93cyB8CgojIyBEZWNpc2lvbgoKKipVc2UgYGV4dGVuc2lvbkF0dHJpYnV0ZTFgIGZvciBPcmdQYXRoLioqIFJlc2VydmUgYGV4dGVuc2lvbkF0dHJpYnV0ZTJgIGZvciBPcmdQYXRoIGRlcHRoIGxldmVsLiBSZXNlcnZlIGBleHRlbnNpb25BdHRyaWJ1dGUz4oCTNWAgZm9yIGZ1dHVyZSBpZGVudGl0eSB0cmFuc2Zvcm1hdGlvbiBhdHRyaWJ1dGVzLiBEb2N1bWVudCB0aGUgZnVsbCBhbGxvY2F0aW9uIHRhYmxlIGluIHRoZSBjYW5vbiB0byBwcmV2ZW50IGRyaWZ0LgoKIyMjIEF0dHJpYnV0ZSBBbGxvY2F0aW9uIFRhYmxlCgp8IEF0dHJpYnV0ZSB8IFB1cnBvc2UgfCBFeGFtcGxlIFZhbHVlIHwgT2JqZWN0IFR5cGVzIHwKfC0tLXwtLS18LS0tfC0tLXwKfCBgZXh0ZW5zaW9uQXR0cmlidXRlMWAgfCBPcmdQYXRoIOKAlCBjYW5vbmljYWwgb3JnYW5pemF0aW9uYWwgYWRkcmVzcyB8IGBDT1JQL1VTL0VBU1QvQkFMVElNT1JFL0lUYCB8IFVzZXIsIERldmljZSB8CnwgYGV4dGVuc2lvbkF0dHJpYnV0ZTJgIHwgT3JnUGF0aCBEZXB0aCDigJQgaGllcmFyY2h5IGxldmVsIGNvdW50IHwgYDVgIHwgVXNlciwgRGV2aWNlIHwKfCBgZXh0ZW5zaW9uQXR0cmlidXRlM2AgfCBSZXNlcnZlZCDigJQgaWRlbnRpdHkgdHJhbnNmb3JtYXRpb24gfCDigJQgfCDigJQgfAp8IGBleHRlbnNpb25BdHRyaWJ1dGU0YCB8IFJlc2VydmVkIOKAlCBpZGVudGl0eSB0cmFuc2Zvcm1hdGlvbiB8IOKAlCB8IOKAlCB8CnwgYGV4dGVuc2lvbkF0dHJpYnV0ZTVgIHwgUmVzZXJ2ZWQg4oCUIGlkZW50aXR5IHRyYW5zZm9ybWF0aW9uIHwg4oCUIHwg4oCUIHwKfCBgZXh0ZW5zaW9uQXR0cmlidXRlNuKAkzE1YCB8IFVuYWxsb2NhdGVkIOKAlCBhdmFpbGFibGUgZm9yIG90aGVyIHdvcmtsb2FkcyB8IOKAlCB8IOKAlCB8CgojIyBFdmFsdWF0aW9uIE1hdHJpeAoKfCBDcml0ZXJpb24gfCBleHRlbnNpb25BdHRyaWJ1dGVzIHwgQ3VzdG9tIFNlY3VyaXR5IEF0dHJpYnV0ZXMgfCBEaXJlY3RvcnkgRXh0ZW5zaW9ucyB8CnwtLS18LS0tfC0tLXwtLS18CnwgRHluYW1pYyBncm91cCBydWxlcyAodXNlcnMpIHwg4pyFIFN1cHBvcnRlZCB8IOKdjCBOb3Qgc3VwcG9ydGVkIHwg4pyFIFN1cHBvcnRlZCB8CnwgRHluYW1pYyBncm91cCBydWxlcyAoZGV2aWNlcykgfCDinIUgU3VwcG9ydGVkIHwg4p2MIE5vdCBzdXBwb3J0ZWQgfCDinYwgTm90IHN1cHBvcnRlZCB8CnwgQ29uZGl0aW9uYWwgQWNjZXNzIGRldmljZSBmaWx0ZXIgfCDinIUgU3VwcG9ydGVkIHwg4p2MIE5vdCBzdXBwb3J0ZWQgfCDinYwgTm90IHN1cHBvcnRlZCB8CnwgQWRtaW5pc3RyYXRpdmUgVW5pdCBtZW1iZXJzaGlwIHwg4pyFIFN1cHBvcnRlZCB8IOKdjCBOb3Qgc3VwcG9ydGVkIHwg4pyFIFBhcnRpYWwgfAp8IEludHVuZSB2aXNpYmlsaXR5IHwg4pyFIE5hdGl2ZSB8IOKdjCBOb3QgdmlzaWJsZSB8IOKdjCBOb3QgdmlzaWJsZSB8CnwgSFIgaW5ib3VuZCBwcm92aXNpb25pbmcgd3JpdGVhYmxlIHwg4pyFIFllcyB8IOKchSBZZXMgfCDinIUgWWVzIHwKfCBBRCBzeW5jIChjb2V4aXN0ZW5jZSBwZXJpb2QpIHwg4pyFIFZpYSBFbnRyYSBDb25uZWN0IHwg4p2MIENsb3VkLW9ubHkgfCDinIUgVmlhIEVudHJhIENvbm5lY3QgfAp8IEFCQUMgLyBBenVyZSBSQkFDIGNvbmRpdGlvbnMgfCDinYwgTm90IHN1cHBvcnRlZCB8IOKchSBQdXJwb3NlLWJ1aWx0IHwg4p2MIE5vdCBzdXBwb3J0ZWQgfAp8IFN0cnVjdHVyZWQgZGF0YSAvIGF0dHJpYnV0ZSBzZXRzIHwg4p2MIEZsYXQgc3RyaW5ncyB8IOKchSBTZXRzICsgZGVmaW5pdGlvbnMgfCDinYwgRmxhdCB2YWx1ZXMgfAp8IENhcGFjaXR5IHwgMTUgdG90YWwgKHNoYXJlZCkgfCBVbmxpbWl0ZWQgfCBVbmxpbWl0ZWQgfAp8IFNldHVwIHJlcXVpcmVkIHwgTm9uZSB8IEF0dHJpYnV0ZSBzZXQgKyBkZWZpbml0aW9uIGNyZWF0aW9uIHwgQXBwIHJlZ2lzdHJhdGlvbiB8CgojIyMgU2NvcmluZyBTdW1tYXJ5CgotICoqZXh0ZW5zaW9uQXR0cmlidXRlcyoqOiA3LzEwIGNyaXRlcmlhIG1ldCDigJQgdGhlIG9ubHkgb3B0aW9uIHRoYXQgc2F0aXNmaWVzIEFMTCBmaXZlIE9yZ1BhdGggY29uc3VtZXJzCi0gKipDdXN0b20gU2VjdXJpdHkgQXR0cmlidXRlcyoqOiAzLzEwIOKAlCBleGNlbGxlbnQgZm9yIEFCQUMgYnV0IGNhbm5vdCBkcml2ZSBkeW5hbWljIGdyb3VwcywgQ0EsIG9yIEludHVuZQotICoqRGlyZWN0b3J5IEV4dGVuc2lvbnMqKjogNC8xMCDigJQgdW5saW1pdGVkIGNhcGFjaXR5IGJ1dCBubyBkZXZpY2UgZHluYW1pYyBncm91cHMgb3IgQ0EgZmlsdGVycwoKIyMgQ29uc2VxdWVuY2VzCgojIyMgUG9zaXRpdmUKCjEuICoqWmVybyBpbmZyYXN0cnVjdHVyZSBzZXR1cCoqIOKAlCBleHRlbnNpb25BdHRyaWJ1dGVzIGV4aXN0IG9uIGV2ZXJ5IEVudHJhIElEIHRlbmFudCB3aXRoIG5vIHByb3Zpc2lvbmluZyByZXF1aXJlZAoyLiAqKkZ1bGwgY29uc3VtZXIgY292ZXJhZ2UqKiDigJQgVGhlIG9ubHkgYXR0cmlidXRlIHR5cGUgdXNhYmxlIGluIGR5bmFtaWMgZ3JvdXAgcnVsZXMgKHVzZXJzICsgZGV2aWNlcyksIENBIGRldmljZSBmaWx0ZXJzLCBBVSBtZW1iZXJzaGlwLCBBTkQgSW50dW5lIHNjb3BlIHRhZ3Mgc2ltdWx0YW5lb3VzbHkKMy4gKipBRCBjb2V4aXN0ZW5jZSoqIOKAlCBleHRlbnNpb25BdHRyaWJ1dGVzIHN5bmMgYmlkaXJlY3Rpb25hbGx5IHZpYSBFbnRyYSBDb25uZWN0LCBlbmFibGluZyBPcmdQYXRoIHBvcHVsYXRpb24gZHVyaW5nIHRoZSBoeWJyaWQgcGVyaW9kCjQuICoqSFIgcHJvdmlzaW9uaW5nIG5hdGl2ZSoqIOKAlCBBUEktZHJpdmVuIGluYm91bmQgcHJvdmlzaW9uaW5nIGFuZCBjbG91ZCBIUiBjb25uZWN0b3JzIGNhbiB3cml0ZSBleHRlbnNpb25BdHRyaWJ1dGVzIGRpcmVjdGx5CjUuICoqUHJvdmVuIGF0IHNjYWxlKiog4oCUIE1pY3Jvc29mdCdzIG93biBkb2N1bWVudGF0aW9uIHVzZXMgZXh0ZW5zaW9uQXR0cmlidXRlcyBmb3Igb3JnYW5pemF0aW9uYWwgaGllcmFyY2h5IGV4YW1wbGVzCgojIyMgTmVnYXRpdmUKCjEuICoqQ2FwYWNpdHkgY29uc3RyYWludCoqIOKAlCBPbmx5IDE1IHNsb3RzIHRvdGFsLCBzaGFyZWQgd2l0aCBFeGNoYW5nZSBPbmxpbmUgYW5kIGFueSBleGlzdGluZyB1c2FnZS4gVGhlIGFsbG9jYXRpb24gdGFibGUgYWJvdmUgcmVzZXJ2ZXMgNSBmb3IgaWRlbnRpdHkgdHJhbnNmb3JtYXRpb24sIGxlYXZpbmcgMTAgZm9yIG90aGVyIHdvcmtsb2Fkcy4KMi4gKipGbGF0IHN0cmluZyBvbmx5Kiog4oCUIE5vIHN0cnVjdHVyZWQgZGF0YSwgbm8gYXR0cmlidXRlIHNldHMsIG5vIHR5cGVkIHZhbGlkYXRpb24uIE9yZ1BhdGggZm9ybWF0IGVuZm9yY2VtZW50IG11c3QgYmUgaGFuZGxlZCBieSB0aGUgcHJvdmlzaW9uaW5nIHBpcGVsaW5lLCBub3QgdGhlIGF0dHJpYnV0ZSBzY2hlbWEuCjMuICoqTm8gQUJBQyoqIOKAlCBleHRlbnNpb25BdHRyaWJ1dGVzIGNhbm5vdCBiZSB1c2VkIGluIEF6dXJlIFJCQUMgY29uZGl0aW9uIGV4cHJlc3Npb25zLiBBdXRob3JpemF0aW9uIHNjZW5hcmlvcyByZXF1aXJpbmcgYXR0cmlidXRlLWJhc2VkIGFjY2VzcyBjb250cm9sIHNob3VsZCB1c2UgQ3VzdG9tIFNlY3VyaXR5IEF0dHJpYnV0ZXMgc2VwYXJhdGVseS4KNC4gKipDb2xsaXNpb24gcmlzayoqIOKAlCBBbnkgZXhpc3RpbmcgZXh0ZW5zaW9uQXR0cmlidXRlMSB1c2FnZSBtdXN0IGJlIGludmVudG9yaWVkIGFuZCBtaWdyYXRlZCBiZWZvcmUgT3JnUGF0aCBkZXBsb3ltZW50LiBEaXNjb3Zlcnkgc2NyaXB0IEQxLjEgaW5jbHVkZXMgdGhpcyBjaGVjay4KCiMjIyBDb21wbGVtZW50YXJ5IFVzZSBvZiBDdXN0b20gU2VjdXJpdHkgQXR0cmlidXRlcwoKQ3VzdG9tIFNlY3VyaXR5IEF0dHJpYnV0ZXMgcmVtYWluIHRoZSBjb3JyZWN0IGNob2ljZSBmb3I6CgotIEFCQUMtZHJpdmVuIGF1dGhvcml6YXRpb24gKGUuZy4sIHNlY3VyaXR5IGNsZWFyYW5jZSBsZXZlbCwgZGF0YSBjbGFzc2lmaWNhdGlvbiBhY2Nlc3MpCi0gU2VydmljZSBwcmluY2lwYWwgYW5kIG1hbmFnZWQgaWRlbnRpdHkgbWV0YWRhdGEKLSBTY2VuYXJpb3Mgd2hlcmUgc3RydWN0dXJlZCBhdHRyaWJ1dGUgc2V0cyB3aXRoIGRlZmluZWQgdmFsdWUgdHlwZXMgYWRkIGdvdmVybmFuY2UgdmFsdWUKClRoZXNlIHVzZSBjYXNlcyBkbyBOT1Qgb3ZlcmxhcCB3aXRoIE9yZ1BhdGgncyByb2xlIGFzIGEgZ3JvdXBpbmcvdGFyZ2V0aW5nIG1lY2hhbmlzbS4gVGhlIHR3byBhdHRyaWJ1dGUgdHlwZXMgYXJlIGNvbXBsZW1lbnRhcnksIG5vdCBjb21wZXRpbmcuCgojIyBDb21wbGlhbmNlIE5vdGVzCgotICoqR0NDLU1vZGVyYXRlKio6IGV4dGVuc2lvbkF0dHJpYnV0ZXMgYXJlIGZ1bGx5IHN1cHBvcnRlZCBpbiBHQ0MtTW9kZXJhdGUgTTM2NSB0ZW5hbnRzCi0gKipGZWRSQU1QKio6IE5vIGJvdW5kYXJ5IGltcGxpY2F0aW9ucyDigJQgZXh0ZW5zaW9uQXR0cmlidXRlcyBhcmUgc3RhbmRhcmQgRW50cmEgSUQgc2NoZW1hCi0gKipVSUFPIENhbm9uKio6IFRoaXMgQURSIHN1cGVyc2VkZXMgdGhlICJUQkQiIG5vdGF0aW9uIGluIFVJQU9fMTM1IFNlY3Rpb24gNSBSZWZpbmVtZW50IE5vdGVzIHJlZ2FyZGluZyBPcmdQYXRoIGF0dHJpYnV0ZSBpbXBsZW1lbnRhdGlvbgoKIyMgUmVmZXJlbmNlcwoKLSBVSUFPXzEzNSDigJQgSWRlbnRpdHkgJiBEaXJlY3RvcnkgVHJhbnNmb3JtYXRpb24gSW52ZW50b3J5LCBUcmFuc2Zvcm1hdGlvbiAjMQotIFVJQU9fMTM2IOKAlCBQcmlvcml0eSAxIFByb2plY3QgUGxhbnMsIGFsbCAzIHNwZWNzIHJlZmVyZW5jZSBPcmdQYXRoCi0gQURSLTAzNSDigJQgT3JnUGF0aCBDb2RlYm9vayBCaW5kaW5nCi0gQURSLTAzNiDigJQgRHluYW1pYyBHcm91cCBQcm92aXNpb25pbmcKLSBBRFItMDM3IOKAlCBBZG1pbiBVbml0IFByb3Zpc2lvbmluZwotIEFEUi0wMzgg4oCUIERldmljZSBQbGFuZSBPcmdQYXRoCi0gQURSLTAzOSDigJQgUG9saWN5IFRhcmdldGluZwo=
"@

$target_0 = Join-Path $RepoRoot "src\uiao\canon\adr\adr-048-orgpath-attribute-selection.md"
Write-B64File -Base64 $b64_0 -TargetPath $target_0 -Label "ADR-048 (OrgPath Attribute Selection)"

# --- Spec 1 D1.1 ? AD Computer Object Inventory ---
$b64_1 = @"
PCMKLlNZTk9QU0lTCiAgICBVSUFPIFNwZWMgMSDigJQgRDEuMTogQUQgQ29tcHV0ZXIgT2JqZWN0IEludmVudG9yeQouREVTQ1JJUFRJT04KICAgIEZ1bGwgZXhwb3J0IG9mIGFsbCBjb21wdXRlciBvYmplY3RzIGZyb20gYWxsIEFEIGRvbWFpbnMvZm9yZXN0cy4KICAgIENvbGxlY3RzOiBETiwgT1MsIE9TIHZlcnNpb24sIGxhc3QgbG9nb24gdGltZXN0YW1wLCBPVSBwYXRoLAogICAgbWFuYWdlZC1ieSwgU1BOIGxpc3QsIEJpdExvY2tlciByZWNvdmVyeSBrZXlzIHByZXNlbnQsCiAgICBMQVBTIHBhc3N3b3JkIGFnZSwgZXh0ZW5zaW9uQXR0cmlidXRlMSAoT3JnUGF0aCBiYXNlbGluZSkuCgogICAgT3V0cHV0cyBzdHJ1Y3R1cmVkIEpTT04gZm9yIGRvd25zdHJlYW0gY29uc3VtcHRpb24gYnkKICAgIEQxLjIgKERldmljZSBTdGF0ZSBDbGFzc2lmaWNhdGlvbikgYW5kIEQxLjkgKE1pZ3JhdGlvbiBSZWFkaW5lc3MpLgoKICAgIFJlZjogVUlBT18xMzYgU3BlYyAxLCBQaGFzZSAxLCBEZWxpdmVyYWJsZSBEMS4xCiAgICAgICAgICBBRFItMDQ4IChleHRlbnNpb25BdHRyaWJ1dGUxID0gT3JnUGF0aCkKLlBBUkFNRVRFUiBPdXRwdXRQYXRoCiAgICBEaXJlY3RvcnkgZm9yIEpTT04gb3V0cHV0LiBEZWZhdWx0cyB0byAuXG91dHB1dAouUEFSQU1FVEVSIERvbWFpbkNvbnRyb2xsZXIKICAgIFRhcmdldCBhIHNwZWNpZmljIERDLiBJZiBvbWl0dGVkLCB1c2VzIHRoZSBuZWFyZXN0IERDIHZpYSBhdXRvLWRpc2NvdmVyeS4KLlBBUkFNRVRFUiBJbmNsdWRlU3RhbGUKICAgIEluY2x1ZGUgY29tcHV0ZXIgb2JqZWN0cyB3aXRoIG5vIGxvZ29uIGluIHRoZSBsYXN0IDM2NSBkYXlzLgogICAgRGVmYXVsdDogJHRydWUgKGluY2x1ZGUgZXZlcnl0aGluZyBmb3IgZnVsbCBpbnZlbnRvcnkpLgouUEFSQU1FVEVSIFNlYXJjaEJhc2UKICAgIE9wdGlvbmFsIEFEIHNlYXJjaCBiYXNlIChETikuIElmIG9taXR0ZWQsIHNlYXJjaGVzIHRoZSBlbnRpcmUgZG9tYWluLgouRVhBTVBMRQogICAgLlxTcGVjMS1EMS4xLUdldC1BRENvbXB1dGVySW52ZW50b3J5LnBzMQogICAgLlxTcGVjMS1EMS4xLUdldC1BRENvbXB1dGVySW52ZW50b3J5LnBzMSAtT3V0cHV0UGF0aCBDOlxleHBvcnRzIC1Eb21haW5Db250cm9sbGVyIGRjMDEuY29udG9zby5jb20KLk5PVEVTCiAgICBSZXF1aXJlczogQWN0aXZlRGlyZWN0b3J5IFBvd2VyU2hlbGwgbW9kdWxlCiAgICBSZXF1aXJlczogUmVhZCBhY2Nlc3MgdG8gQUQgY29tcHV0ZXIgb2JqZWN0cwogICAgUmVxdWlyZXM6IFJlYWQgYWNjZXNzIHRvIG1zLUZWRS1SZWNvdmVyeUluZm9ybWF0aW9uIChCaXRMb2NrZXIpCiAgICBSZXF1aXJlczogUmVhZCBhY2Nlc3MgdG8gbXMtTWNzLUFkbVB3ZCAvIG1zTEFQUy1QYXNzd29yZCAoTEFQUykKIz4K
"@

$target_1 = Join-Path $RepoRoot "tools\discovery\Spec1-D1.1-Get-ADComputerInventory.ps1"
Write-B64File -Base64 $b64_1 -TargetPath $target_1 -Label "Spec 1 D1.1 ? AD Computer Object Inventory"

# --- Spec 2 D1.1 ? HR Attribute Schema Discovery (reconstructed) ---
# New script: discovers HR-related attributes on user objects and exports schema + sample values.

$b64_2 = @"
IyBTcGVjIDIgRDEuMSAtIEhSIEF0dHJpYnV0ZSBTY2hlbWEgRGlzY292ZXJ5CiMgRnVsbCBkaXNjb3Zlcnkgb2YgSFIvRU1QTC1yZWxldmFudCBhdHRyaWJ1dGVzIG9uIEFjdGl2ZSBEaXJlY3RvcnkgdXNlciBvYmplY3RzLgpwYXJhbSgKICAgIFtzdHJpbmddJE91dHB1dFBhdGggPSAuXG91dHB1dCwKICAgIFtzdHJpbmddJFNlYXJjaEJhc2UsCiAgICBbYm9vbF0kSW5jbHVkZURpc2FibGVkID0gJHRydWUKKQoKJEVycm9yQWN0aW9uUHJlZmVyZW5jZSA9ICJTdG9wIgoKaWYgKC1ub3QgKEdldC1Nb2R1bGUgLUxpc3RBdmFpbGFibGUgLU5hbWUgQWN0aXZlRGlyZWN0b3J5KSkgewogICAgV3JpdGUtRXJyb3IgIkFjdGl2ZURpcmVjdG9yeSBtb2R1bGUgbm90IGZvdW5kLiBJbnN0YWxsIFJTQVQgb3IgcnVuIG9uIGEgZG9tYWluLWpvaW5lZCBtYWNoaW5lIHdpdGggQUQgdG9vbHMuIgogICAgcmV0dXJuCn0KSW1wb3J0LU1vZHVsZSBBY3RpdmVEaXJlY3RvcnkgLUVycm9yQWN0aW9uIFN0b3AKCmlmICgtbm90IChUZXN0LVBhdGggJE91dHB1dFBhdGgpKSB7CiAgICBOZXctSXRlbSAtUGF0aCAkT3V0cHV0UGF0aCAtSXRlbVR5cGUgRGlyZWN0b3J5IC1Gb3JjZSB8IE91dC1OdWxsCn0KCiRkb21haW4gPSAoR2V0LUFERG9tYWluKS5ETlNSb290CiR0aW1lc3RhbXAgPSBHZXQtRGF0ZSAtRm9ybWF0ICJ5eXl5TU1kZC1ISG1tc3MiCiRvdXRGaWxlID0gSm9pbi1QYXRoICRPdXRwdXRQYXRoICJVSUFPX1NwZWMyX0QxLjFfSFJBdHRyaWJ1dGVTY2hlbWFfJGRvbWFpbl8kdGltZXN0YW1wLmpzb24iCgpXcml0ZS1Ib3N0ICJVIUFPIFNwZWMgMiBEMS4xIC0gSFIgQXR0cmlidXRlIFNjaGVtYSBEaXNjb3ZlcnkiIC1Gb3JlZ3JvdW5kQ29sb3IgQ3lhbgpXcml0ZS1Ib3N0ICIgIERvbWFpbjogJGRvbWFpbiIgLUZvcmVncm91bmRDb2xvciBDeWFuCldyaXRlLUhvc3QgIiAgVGltZXN0YW1wOiAkdGltZXN0YW1wIiAtRm9yZWdyb3VuZENvbG9yIEN5YW4KCgokc2VhcmNoUGFyYW1zID0gQHsKICAgIFNlYXJjaEJhc2UgPSBpZiAoJFNlYXJjaEJhc2UpIHsgJFNlYXJjaEJhc2UgfSBlbHNlIHsgIkRvbWFpbiByb290IiB9CiAgICBGaWx0ZXIgICAgPSAnKHVzZXJBY2NvdW50KSd9CgojIENvbGxlY3QgdXNlciBvYmplY3RzCldyaXRlLUhvc3QgIiAgUXVlcnlpbmcgQUQgZm9yIHVzZXIgb2JqZWN0cy4uLiIgLUZvcmVncm91bmRDb2xvciBZZWxsb3cKJHVzZXJzID0gR2V0LUFERXNlck9iamVjdCBAc2VhcmNoUGFyYW1zIC1Qcm9wZXJ0aWVzICogLUVycm9yQWN0aW9uIFN0b3AKV3JpdGUtSG9zdCAiICBGb3VuZCAkKCR1c2Vycy5Db3VudCkgdXNlciBvYmplY3RzIiAtRm9yZWdyb3VuZENvbG9yIEdyZWVuCgojIEJ1aWxkIGF0dHJpYnV0ZSBzY2hlbWEgZnJvbSBzYW1wbGUgb2YgdXNlcnMKJHNhbXBsZSA9ICR1c2VycyB8IFNlbGVjdCAtRmlyc3QgMTAwCmlmICgkbm90JHNhbXBsZSkgewogICAgV3JpdGUtRXJyb3IgIk5vIHVzZXIgb2JqZWN0cyByZXR1cm5lZC4iCiAgICByZXR1cm4KfQoKJGF0dHJpYnV0ZXMgPSBuZXctT2JqZWN0IFN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkxpc3Rbb2JqZWN0XQpmb3JlYWNoICgkdSBpbiAkc2FtcGxlKSB7CiAgICAkdS5Qcm9wZXJ0aWVzLk5hbWVzIHwKICAgICAgICBGb3JFYWNoLUpvYmplY3QgewogICAgICAgICAgICBpZiAoLW5vdCAkYXR0cmlidXRlcy5Db250YWlucygkXykpIHsKICAgICAgICAgICAgICAgIFt2b2lkXSRudWxsID0gJGF0dHJpYnV0ZXMuQWRkKCRfKQogICAgICAgICAgICB9CiAgICAgICAgfQp9CgojIEJ1aWxkIHNjaGVtYSB3aXRoIHR5cGUgYW5kIHNhbXBsZSB2YWx1ZXMKJHNjaGVtYSA9IFtzeXN0ZW0uQ29sbGVjdGlvbnMuR2VuZXJpYy5MaXN0W29iamVjdF1dOjpOZXcoKQpmb3JlYWNoICgkYXR0ciBpbiAkYXR0cmlidXRlcykgewogICAgJHZhbHVlcyA9ICRzYW1wbGUgfCBTZWxlY3QtT2JqZWN0IHskXy5JdGVtKCkkYXR0ciB9IHwgV2hlcmUtT2JqZWN0IHsgJF8gfQogICAgJHR5cGUgPSAiVW5rbm93biIKICAgIGlmICgkdmFsdWVzKSB7CiAgICAgICAgJHR5cGUgPSAoJHZhbHVlcy5HZXRUeXBlKCkpLk5hbWUKICAgIH0KICAgICRzYW1wbGVWYWx1ZSA9ICRudWxsCiAgICBpZiAoJHZhbHVlcykgewogICAgICAgICRzYW1wbGVWYWx1ZSA9ICgkdmFsdWVzIHwgU2VsZWN0IC1GaXJzdCAxKQogICAgfQogICAgJHNjaGVtYS5BZGQoW3BzY3VzdG9tLm1hbmFnZW1lbnQuQXV0b21hdGlvbi5QU0N1c3RvbV0gewogICAgICAgIEF0dHJpYnV0ZU5hbWUgPSAkYXR0cgogICAgICAgIFR5cGUgICAgICAgID0gJHR5cGUKICAgICAgICBTYW1wbGVWYWx1ZSA9ICRzYW1wbGVWYWx1ZQogICAgfSkKfQoKIyBGb2N1cyBvbiBsaWtlbHkgSFIvRU1QTC1yZWxldmFudCBhdHRyaWJ1dGVzCiRockludGVyZXN0ID0gJHNjaGVtYSB8IFdoZXJlLU9iamVjdCB7CiAgICAkXy5BdHRyaWJ1dGVOYW1lIC1tYXRjaCAiKihlbXBsb3llZXJ8bWFuYWdlcnxkZXBhcnRtZW50fG9yZ1BhdGh8bG9jYXRpb24pfCIKfQoKJHN1bW1hcnkgPSBbb3JkZXJlZF1AewogICAgRXhwb3J0TWV0YWRhdGEgPSBbb3JkZXJlZF1AewogICAgICAgIERvbWFpbiA9ICRkb21haW4KICAgICAgICBUaW1lc3RhbXAgPSAkdGltZXN0YW1wCiAgICAgICAgU2NyaXB0ICA9ICJVSUFPIFNwZWMgMiBEMS4xIC0gSFIgQXR0cmlidXRlIFNjaGVtYSBEaXNjb3ZlcnkiCiAgICB9CiAgICBTdGF0aXN0aWNzID0gW29yZGVyZWRdQHsKICAgICAgICBUb3RhbEF0dHJpYnV0ZXMgPSAkc2NoZW1hLkNvdW50CiAgICAgICAgSFJJbnRlcmVzdCAgICAgPSAkaHJJbnRlcmVzdC5Db3VudAogICAgfQp9CgoKb3V0cHV0ID0gW29yZGVyZWRdQHsKICAgIFN1bW1hcnkgPSAkc3VtbWFyeQogICAgQXR0cmlidXRlcyA9ICRzY2hlbWEKfQoKb3V0cHV0IHwgQ29udmVydC1Ub0pzb24gLURlcHRoIDEwIHwgT3V0LUZpbGUgLUZpbGVQYXRoICRvdXRGaWxlIC1FbmNvZGluZyB1dGY4Tm9CT00KV3JpdGUtSG9zdCAiICBPdXRwdXQ6ICRvdXRGaWxlIiAtRm9yZWdyb3VuZENvbG9yIEdyZWVuCg==
"@

$target_2 = Join-Path $RepoRoot "tools\discovery\Spec2-D1.1-Get-HRAttributeSchema.ps1"
Write-B64File -Base64 $b64_2 -TargetPath $target_2 -Label "Spec 2 D1.1 ? HR Attribute Schema Discovery"

# --- Architecture diagram 1 ? OrgPath logical model (PlantUML) ---
$orgPathDiagram1 = @"
@startuml
title OrgPath logical model (UIAO)

skinparam backgroundColor #FFFFFF
skinparam classAttributeIconSize 0
skinparam defaultTextAlignment left

package ""Identity sources"" {
  class HR_System {
    +EmployeeID
    +Department
    +ManagerID
    +Location
  }

  class AD_User {
    +sAMAccountName
    +userPrincipalName
    +extensionAttribute1  // OrgPath (canonical)
    +extensionAttribute2  // OrgPath depth
  }

  class AD_Computer {
    +dNSHostName
    +extensionAttribute1  // OrgPath (canonical)
  }
}

package ""OrgPath pipeline"" {
  class OrgPath_Resolver {
    +Resolve(userOrDevice) : OrgPath
    +Validate(path) : bool
  }

  class OrgPath_Rules {
    +HR_to_OrgPath()
    +AD_Fallback()
  }
}

package ""Consumers"" {
  class Dynamic_Groups
  class Conditional_Access
  class Admin_Units
  class Intune_Scopes
}

HR_System --> OrgPath_Resolver : HR attributes
AD_User --> OrgPath_Resolver : extensionAttribute1/2
AD_Computer --> OrgPath_Resolver : extensionAttribute1

OrgPath_Resolver --> OrgPath_Rules
OrgPath_Resolver --> Dynamic_Groups
OrgPath_Resolver --> Conditional_Access
OrgPath_Resolver --> Admin_Units
OrgPath_Resolver --> Intune_Scopes

@enduml
"@

$diagram1Target = Join-Path $RepoRoot "src\uiao\canon\diagrams\orgpath-logical-model.puml"
[IO.Directory]::CreateDirectory((Split-Path $diagram1Target -Parent)) | Out-Null
[IO.File]::WriteAllText($diagram1Target, $orgPathDiagram1, [Text.Encoding]::UTF8)
Write-Host "Writing OrgPath logical model diagram..."
Write-Host "  OK  $diagram1Target" -ForegroundColor Green

# --- Architecture diagram 2 ? OrgPath data flow (PlantUML) ---
$orgPathDiagram2 = @"
@startuml
title OrgPath data flow (UIAO)

skinparam backgroundColor #FFFFFF
skinparam defaultTextAlignment left

actor HR as ""HR System""
actor AD as ""Active Directory""
actor Entra as ""Entra ID""
actor Admin as ""Admin / Operator""

rectangle ""HR / Source systems"" {
  HR --> (HR Export)
}

rectangle ""Identity platform"" {
  (HR Export) --> AD : HR-driven join\n(EmployeeID, Manager, Dept)
  AD --> (OrgPath Stamping Script) : extensionAttribute1/2
  (OrgPath Stamping Script) --> Entra : sync via AAD Connect
}

rectangle ""Policy & governance"" {
  Entra --> (Dynamic Groups)
  Entra --> (Conditional Access)
  Entra --> (Admin Units)
  Entra --> (Intune Scopes)
}

Admin --> (OrgPath Stamping Script) : configure rules\nand mappings
Admin --> Entra : validate groups\nand policy targeting

@enduml
"@

$diagram2Target = Join-Path $RepoRoot "src\uiao\canon\diagrams\orgpath-data-flow.puml"
[IO.Directory]::CreateDirectory((Split-Path $diagram2Target -Parent)) | Out-Null
[IO.File]::WriteAllText($diagram2Target, $orgPathDiagram2, [Text.Encoding]::UTF8)
Write-Host "Writing OrgPath data flow diagram..."
Write-Host "  OK  $diagram2Target" -ForegroundColor Green

Write-Host "Write-CanonFiles2.ps1 completed." -ForegroundColor Cyan
