@startuml
skinparam defaultTextAlignment left
skinparam packageStyle rectangle
skinparam shadowing false

package "Planes" {
  [Identity Plane]
  [Device Plane]
  [Access Plane]
  [Network Plane]
  [Governance Plane]
  [Workload Plane]
  [Application Plane]
}

' Identity impacts
[Identity Plane] --> [Access Plane]
[Identity Plane] --> [Governance Plane]
[Identity Plane] --> [Workload Plane]
[Identity Plane] --> [Application Plane]

' Device impacts
[Device Plane] --> [Access Plane]
[Device Plane] --> [Governance Plane]
[Device Plane] --> [Application Plane]

' Access impacts
[Access Plane] --> [Identity Plane]
[Access Plane] --> [Application Plane]
[Access Plane] --> [Governance Plane]
[Access Plane] --> [Workload Plane]

' Network impacts
[Network Plane] --> [Access Plane]
[Network Plane] --> [Governance Plane]
[Network Plane] --> [Application Plane]

' Governance impacts
[Governance Plane] --> [Identity Plane]
[Governance Plane] --> [Device Plane]
[Governance Plane] --> [Access Plane]
[Governance Plane] --> [Network Plane]
[Governance Plane] --> [Workload Plane]
[Governance Plane] --> [Application Plane]

' Workload impacts
[Workload Plane] --> [Application Plane]
[Workload Plane] --> [Governance Plane]

' Application impacts
[Application Plane] --> [Governance Plane]
[Application Plane] --> [Workload Plane]

@enduml
